# Generated by Django 3.0.6 on 2020-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('logo', models.ImageField(default='', upload_to='images/currency')),
            ],
        ),
    ]
