# Generated by Django 3.0.6 on 2020-05-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency_id',
        ),
    ]
